import { v7 } from 'uuid'

// Every row id is a UUIDv7 generated by the client or the API (never by the DB), so creates can be
// retried safely (idempotent creates, docs/DATA_MODEL.md §1.2) and ids sort by creation time.

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/** A new UUIDv7 (time-ordered; monotonic within this process). */
export function newId(): string {
  return v7()
}

/** True when the value is a UUID in canonical 8-4-4-4-12 hex form (any version). */
export function isUuid(value: unknown): value is string {
  return typeof value === 'string' && UUID_PATTERN.test(value)
}
