import { z } from 'zod'
import { BUSINESS_NAME_MAX_LENGTH } from '../business'
import { zUuid } from '../primitives'
import { CONTROL_CHARACTER } from '../text'
import { localeDto } from './me'

// Smart Setup on the wire (docs/PRODUCT.md §6). The shape is checked here; the question set, its skip
// logic and the review rules live in @bizcost/modules, which the server applies strictly
// (parseSetupAnswers, applyAdjustments): nothing the client computed is trusted.

const setupId = z.string().min(1).max(40)

/** The business name from step 0: 1–100 characters after trimming, one line (no control characters). */
export const businessNameInput = z
  .string()
  .trim()
  .min(1)
  .max(BUSINESS_NAME_MAX_LENGTH)
  .refine((value) => !CONTROL_CHARACTER.test(value), { message: 'control character' })

/** Answers by question id: an option id, a boolean (yes/no) or a list of option ids. */
export const setupAnswersInput = z
  .record(setupId, z.union([setupId, z.boolean(), z.array(setupId).max(10)]))
  .refine((answers) => Object.keys(answers).length <= 20, { message: 'too many answers' })

/** The review changes: the final state of each module or capability the user switched. */
export const setupAdjustmentsInput = z.object({
  modules: z.array(z.object({ id: setupId, enabled: z.boolean() })).max(40),
  capabilities: z.array(z.object({ key: setupId, enabled: z.boolean() })).max(20),
})

/**
 * `business.createFromSetup` (authed). `businessId` is generated by the client (UUIDv7) and kept until
 * the business exists, so a retry is idempotent: the same payload returns the same business, another
 * payload is CONFLICT. `locale` names the default location and roles and is the business's default
 * language.
 */
export const createFromSetupInput = z.object({
  businessId: zUuid,
  legalName: businessNameInput,
  locale: localeDto,
  questionSetVersion: z.int().positive(),
  answers: setupAnswersInput,
  adjustments: setupAdjustmentsInput,
})
export type CreateFromSetupInput = z.input<typeof createFromSetupInput>

export const createFromSetupDto = z.object({ businessId: zUuid })
export type CreateFromSetupDto = z.infer<typeof createFromSetupDto>

/** `account.setLastBusiness` (authed): where to go after sign-in (profiles.last_business_id). */
export const setLastBusinessInput = z.object({ businessId: zUuid })
export type SetLastBusinessInput = z.input<typeof setLastBusinessInput>
